coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        informational: false
    patch:
      backend:
        flags: [backend]
        target: 90%
        threshold: 5%
        informational: false
      frontend:
        flags: [frontend]
        target: 90%
        threshold: 5%
        informational: false

flags:
  backend:
    paths:
      - engine/
      - api/
  frontend:
    paths:
      - frontend/src/

comment:
  layout: "reach,diff,flags"
  behavior: default
